printWidth: 110
tabWidth: 2
useTabs: false
endOfLine: lf
semi: true
singleQuote: true
quoteProps: 'consistent'
jsxSingleQuote: false
trailingComma: 'es5'
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: 'avoid'